[project]
name = "wakeupbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.18.0",
    "bestconfig>=1.3.6",
    "gspread>=6.2.0",
    "pandas>=2.2.3",
]
